export enum Event {
  BANK_SLIP_GENERATED = 'BANK_SLIP_GENERATED',
  BANK_SLIP_EXPIRED = 'BANK_SLIP_EXPIRED',
  PIX_GENERATED = 'PIX_GENERATED',
  PIX_EXPIRED = 'PIX_EXPIRED',
  NUPAY_GENERATED = 'NUPAY_GENERATED',
  NUPAY_EXPIRED = 'NUPAY_EXPIRED',
  PICPAY_GENERATED = 'PICPAY_GENERATED',
  PICPAY_EXPIRED = 'PICPAY_EXPIRED',
  ABANDONED_CART = 'ABANDONED_CART',
  SALE_REFUSED = 'SALE_REFUSED',
  SALE_APPROVED = 'SALE_APPROVED',
  SALE_REFUNDED = 'SALE_REFUNDED',
  SALE_CHARGEBACK = 'SALE_CHARGEBACK',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  TEST = 'TEST',
}

export enum StatusCode {
  SUCCESS = 'SUCCESS',
  EMPTY = 'EMPTY',
  ERROR = 'ERROR',
}
